PUT http://localhost:5000/gambler
Content-Type: application/json

{
    "name": "Paulo",
    "email": "paulo@email.com",
    "phone": "65432",
    "birth_date": "1980-09-27"
}

###
PUT http://localhost:5000/gambler
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@email.com",
    "phone": "12345",
    "birth_date": "1979-09-27"
}

###

GET http://localhost:5000/gambler?email=daniel@email.com

###

GET http://localhost:5000/gambler?email=paulo@email.com

###

GET http://localhost:5000/gambler?email=fulano@email.com

###

PUT http://localhost:5000/bet
Content-Type: application/json

{
    "champion": "Itália",
    "runner_up": "Brasil",
    "gambler_id": "57edfd4a-cc3c-4114-b997-52e9b4cfa987",
    "bet_date": "2023-02-02"
}

###

GET http://localhost:5000/bet

###

GET http://localhost:5000/bet?gambler_id=57edfd4a-cc3c-4114-b997-52e9b4cfa987